default_language_version:
  golang: 1.25.4

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

default_stages:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-added-large-files
        exclude: poetry.lock|uv.lock
      - id: check-ast
      - id: check-yaml
        exclude: mkdocs.yml
        args:
          - --allow-multiple-documents
      - id: check-toml
      - id: check-json
        exclude: .vscode/launch.json
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-ensure-ascii", "--no-sort-keys"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: fix-byte-order-marker
        exclude: docs/CNAME
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-docstring-first
      - id: debug-statements
      - id: check-symlinks

  # shell script linter
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args:
          - --number
          - --no-validate
        additional_dependencies:
          # https://mdformat.readthedocs.io/en/stable/users/plugins.html
          # Code formatter plugins
          - mdformat-beautysh  # bash, sh
          # - mdformat-black  # python
          - mdformat-config  # json, toml, yaml
          - mdformat-gofmt  # go
          # - mdformat-ruff  # python
          # - mdformat-rustfmt  # rust
          # - mdformat-shfmt  # bash, sh
          # - mdformat-web  # javascript, js, css, html, xml
          # Parser extension plugins
          # - mdformat-admon  # admonitions
          # - mdformat-deflist  # definition lists
          - mdformat-footnote  # footnotes
          - mdformat-frontmatter  # front matter
          - mdformat-gfm  # GitHub Flavored Markdown (includes tables)
          - mdformat-gfm-alerts  # GFM alerts
          - mdformat-mkdocs  # MKDocs
          # - mdformat-myst  # MyST
          # - mdformat-toc  # table of contents
          # Other misc plugins
          - mdformat-pyproject  # load options from pyproject.toml
          - mdformat-simple-breaks  # three dashes for breaks
          # Legacy/Additional
          # - mdformat-tables  # deprecated, use mdformat-gfm
          # - mdformat-wikilink  # wikilinks

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
